#!/usr/bin/env bash
# Generate a production .env for Hostinger VPS (app + Postgres on same server).
# Run once:  bash deploy/setup-env.sh
set -euo pipefail

ENV_FILE=".env"
EXAMPLE=".env.example"

if [ -f "$ENV_FILE" ]; then
  echo "!! $ENV_FILE already exists — not overwriting."
  echo "   Edit it manually or delete it first."
  exit 1
fi

gen_secret() {
  openssl rand -base64 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
}

DB_PASS="$(gen_secret | tr -d '/+=' | head -c 32)"
AUTH_SECRET="$(gen_secret)"

read -rp "Domain (e.g. erp.azconsultants.com): " DOMAIN
DOMAIN="${DOMAIN:-erp.azconsultants.com}"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup-env.sh — $(date -Iseconds)

# ── PostgreSQL (runs in Docker on this VPS, internal network only) ──────
POSTGRES_USER=azc
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=az_erp

# App connects to Postgres via the Docker service name "postgres".
DATABASE_URL=postgresql://azc:${DB_PASS}@postgres:5432/az_erp?schema=public

# ── Auth ───────────────────────────────────────────────────────────────
AUTH_SECRET=${AUTH_SECRET}
AUTH_URL=https://${DOMAIN}
NEXTAUTH_URL=https://${DOMAIN}
AUTH_TRUST_HOST=true

# ── App ──────────────────────────────────────────────────────────────────
NODE_ENV=production
UPLOAD_DIR=/app/uploads

# ── Document storage ───────────────────────────────────────────────────
# local = VPS disk (default). Switch to r2 after Cloudflare bucket is ready.
STORAGE_BACKEND=local
# R2_ACCOUNT_ID=
# R2_ACCESS_KEY_ID=
# R2_SECRET_ACCESS_KEY=
# R2_BUCKET=az-erp-documents
EOF

chmod 600 "$ENV_FILE"
echo ""
echo "==> Created $ENV_FILE with random DB password and AUTH_SECRET."
echo "==> Next: update deploy/nginx/app.conf with domain: ${DOMAIN}"
echo "==> For Cloudflare R2 docs storage later: set STORAGE_BACKEND=r2 + R2_* in .env"
echo "==> Then:  bash deploy/deploy.sh"
